services:
  chatbot-db:
    image: postgres:16
    container_name: chatbot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5437:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
